# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)

Cat.create(
  [
    {name: "アーチー", age: 0 },
    {name: "アーロ", age: 1 },
    {name: "アイヴァン", age: 2 },
    {name: "アイリス", age: 3 },
    {name: "アヴァロン", age: 4 },
    {name: "アクセル", age: 5 },
    {name: "あずき", age: 6 },
    {name: "アディ", age: 7 },
    {name: "アディソン", age: 8 },
    {name: "アニー", age: 9 },
    {name: "アビー", age: 10 },
    {name: "アポロ", age: 11 },
    {name: "アリエル", age: 12 },
    {name: "アリス", age: 13 },
    {name: "アルド", age: 14 },
    {name: "アルフィ", age: 15 },
    {name: "アレックス", age: 16 },
    {name: "アンバー", age: 17 },
    {name: "イザベラ", age: 18 },
    {name: "イジィ", age: 19 },
    {name: "ウィスカー", age: 0 },
    {name: "ウィリアム", age: 1 },
    {name: "ウィロー", age: 2 },
    {name: "うに", age: 3 },
    {name: "エイヴァ", age: 4 },
    {name: "エヴァ", age: 5 },
    {name: "エコー", age: 6 },
    {name: "エディ", age: 7 },
    {name: "エマ", age: 8 },
    {name: "エラ", age: 9 },
    {name: "エリー", age: 10 },
    {name: "エルサ", age: 11 },
    {name: "エルビス", age: 12 },
    {name: "エンジェル", age: 13 },
    {name: "オータム", age: 14 },
    {name: "オーティス", age: 15 },
    {name: "オーディン", age: 16 },
    {name: "オードリー", age: 17 },
    {name: "おくら", age: 18 },
    {name: "オジー", age: 19 },
    {name: "オスカー", age: 0 },
    {name: "おもち", age: 1 },
    {name: "オリィ", age: 2 },
    {name: "オリオン", age: 3 },
    {name: "オリバー", age: 4 },
    {name: "オリビア", age: 5 },
    {name: "オレオ", age: 6 },
    {name: "ガーフィールド", age: 7 },
    {name: "かい", age: 8 },
    {name: "カエサル", age: 9 },
    {name: "ガナー", age: 10 },
    {name: "カリー", age: 11 },
    {name: "キキ", age: 12 },
    {name: "ギズモ", age: 13 },
    {name: "キティ", age: 14 },
    {name: "きなこ", age: 15 },
    {name: "キャスパー", age: 16 },
    {name: "キャンディ", age: 17 },
    {name: "ぎんじ", age: 18 },
    {name: "クイナ", age: 19 },
    {name: "くう", age: 0 },
    {name: "グース", age: 1 },
    {name: "クーパー", age: 2 },
    {name: "クッキー", age: 3 },
    {name: "クラッシュ", age: 4 },
    {name: "グリフィン", age: 5 },
    {name: "グレイシー", age: 6 },
    {name: "グレース", age: 7 },
    {name: "クレオ", age: 8 },
    {name: "くろ", age: 9 },
    {name: "クロエ", age: 10 },
    {name: "ケイシー", age: 11 },
    {name: "ケイティ", age: 12 },
    {name: "ケティ", age: 13 },
    {name: "ここ", age: 14 },
    {name: "コスモ", age: 15 },
    {name: "こたろう", age: 16 },
    {name: "こてつ", age: 17 },
    {name: "コナ", age: 18 },
    {name: "ゴンゾ", age: 19 },
    {name: "サーシャ", age: 0 },
    {name: "さくら", age: 1 },
    {name: "サシー", age: 2 },
    {name: "サディ", age: 3 },
    {name: "サミー", age: 4 },
    {name: "サム", age: 5 },
    {name: "サレム", age: 6 },
    {name: "シーダ", age: 7 },
    {name: "ジェイク", age: 8 },
    {name: "シェビー", age: 9 },
    {name: "ジギー", age: 10 },
    {name: "じじ", age: 11 },
    {name: "ししまる", age: 12 },
    {name: "シナモン", age: 13 },
    {name: "シバ", age: 14 },
    {name: "ジプシー", age: 15 },
    {name: "ジャスティス", age: 16 },
    {name: "ジャスパー", age: 17 },
    {name: "ジャスミン", age: 18 },
    {name: "ジャック", age: 19 },
  ]
)
